//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP223_Nikolaeva_WPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterService
    {
        public int ID { get; set; }
        public int MasterID { get; set; }
        public int ServCategotyID { get; set; }
        public decimal Price { get; set; }
    
        public virtual ServCategory ServCategory { get; set; }
        public virtual User User { get; set; }
    }
}
