//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP223_Nikolaeva_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int TargetTypeID { get; set; }
        public int TargetID { get; set; }
        public System.DateTime Date { get; set; }
        public int ReasonID { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
    
        public virtual ComplaintReason ComplaintReason { get; set; }
        public virtual ComplaintTargetType ComplaintTargetType { get; set; }
        public virtual User User { get; set; }
    }
}
