//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP223_Nikolaeva_WPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PR14_CinemaEntities : DbContext
    {
        public PR14_CinemaEntities()
            : base("name=PR14_CinemaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Age_Rating> Age_Rating { get; set; }
        public virtual DbSet<Film> Film { get; set; }
        public virtual DbSet<Film_Genre> Film_Genre { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<Kinozal> Kinozal { get; set; }
        public virtual DbSet<Kinozal_Rating> Kinozal_Rating { get; set; }
        public virtual DbSet<Seans> Seans { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
