//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP223_Nikolaeva_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int HotelId { get; set; }
        public int Cleanliness { get; set; }
        public int Service { get; set; }
        public int Comfort { get; set; }
        public int LocationScore { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<double> TotalRating { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual User User { get; set; }
        public virtual Category Category { get; set; }
    }
}
