//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP223_Nikolaeva_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seans_Seat
    {
        public int ID { get; set; }
        public int Seans_ID { get; set; }
        public int Seat_ID { get; set; }
    
        public virtual Seans Seans { get; set; }
        public virtual Seat Seat { get; set; }
    }
}
